# Generated by Django 5.2 on 2025-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_alter_prediction_probability_away_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
