# Generated by Django 5.2 on 2025-05-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50)),
                ('player_id', models.CharField(max_length=50)),
                ('player_name', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=50)),
                ('batting_position', models.IntegerField()),
                ('runs_scored', models.IntegerField()),
                ('balls_faced', models.IntegerField()),
                ('strike_rate', models.FloatField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('how_out', models.CharField(max_length=100)),
                ('bowler_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50)),
                ('player_id', models.CharField(max_length=50)),
                ('player_name', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=50)),
                ('runs_conceded', models.IntegerField()),
                ('total_overs', models.FloatField()),
                ('economy', models.FloatField()),
                ('dots', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('wide', models.IntegerField()),
                ('no_balls', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('venue', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(max_length=10)),
                ('team_1', models.CharField(max_length=100)),
                ('team_2', models.CharField(max_length=100)),
                ('team_1_score', models.IntegerField()),
                ('team_1_wicket', models.IntegerField()),
                ('team_2_score', models.IntegerField()),
                ('team_2_wicket', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
                ('loser', models.CharField(max_length=100)),
                ('player_of_the_match', models.CharField(max_length=100)),
                ('umpire_1', models.CharField(max_length=100)),
                ('umpire_2', models.CharField(max_length=100)),
            ],
        ),
    ]
